# 4장 NumPy 기본: 배열과 벡터 연산

Numpy : Numerical Python

Numpy에서 제공하는 것들
- 효율적인 다차원 배열인 ndarray는 빠른 배열 계산과 유연한 ***브로드캐스팅*** 기능 제공
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구
- 선형대수, 난수 생성기, 푸리에 변환 가능
- C, C++, 포트란으로 작성한 코드를 연결 가능한 C API

백만 개의 정수를 저장하는 Numpy배열과 파이썬 리스트 비교하기

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

이제 각각의 배열과 리스트 원소에 2를 곱해보자

In [5]:
%time for _ in range(10): my_arr = my_arr*2

CPU times: total: 15.6 ms
Wall time: 11 ms


In [6]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: total: 453 ms
Wall time: 462 ms


NumPy를 사용한 코드가 순수 파이썬으로 작성한 코드보다 열 배에서 백 배 이상 빠르고 메모리도 더 적게 사용

## 4.1 NumPy ndarray: 다차원 배열 객체

In [9]:
import numpy as np

ndarray란?
- N차원의 배열 객체
- 파이썬에서 사욯라 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조

먼저 NumPy 패키지를 임포트하고 임의의 값이 들어 있는 작은 배열을 만들자

In [10]:
#임의의 값 생성
data = np.random.randn(2,3)

In [11]:
data

array([[-1.87328745, -0.91060963, -0.44828942],
       [-0.72467232, -1.41206136, -0.25923788]])

그리고 그 값에 산술 연산을 해보자

In [12]:
data*10

array([[-18.73287453,  -9.10609626,  -4.48289417],
       [ -7.2467232 , -14.12061358,  -2.59237879]])

In [13]:
data+data

array([[-3.74657491, -1.82121925, -0.89657883],
       [-1.44934464, -2.82412272, -0.51847576]])

ndarray : 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열<br>
ndarray의 모든 원소는 같은 자료형<br>
모든 배열은 각 차원의 크기를 알려주는 shape라는 튜플과 배열에 저장된 ***자료형***을 알려주는 dtype이라는 객체를 가짐

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

### 4.1.1 ndarray 생성

배열은 생성하는 가장 쉬운 방법 : array 함수 이용<br>
파이썬의 리스트는 변환하기 좋은 예

In [19]:
data1 = [6,7.5,8,0,1]

In [20]:
arr1 = np.array(data1)

In [21]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

같은 길이를 가지는 리스트를 내포하고 있는 순차 데이터는 다차원 배열로 변환 가능

In [22]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [23]:
arr2 = np.array(data2)

In [24]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

data2는 리스트를 담고 있는 리스트이므로 Numpy 배열인 arr2는 해당 데이터로부터 형태를 추론해 2차원 형태로 생성됨<br>
ndim과 shape 속성을 검사해 이를 확인 가능

In [25]:
arr2.ndim

2

In [26]:
arr2.shape

(2, 4)

명시적으로 지정하지 않는 한 np.array는 생성될 때 적절한 자료형을 추론<br>
그렇게 추론된 자료형은 dtype 객체에 저장됨<br>
다차원 배열 생성 시 원하는 형태의 튜플 넘기기

In [27]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

np.array는 새로운 배열을 생성하기 위한 여러 함수를 가진다
- zeros와 ones: 주어진 길이나 모양에 각각 0과 1이 들어 잇는 배열 생성
- empty함수 : 초기화되지 않는 배열 생성

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros((2,3,2)) #삼차원

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

***CAUTION_*** np.empty는 0으로 초기화된 배열 반환 X<br>
대부분의 경우 np.empty는 초기화되지 않는 '가비지' 값으로 채워진 배열 반환

arange는 파이썬의 range 함수의 배열 버전

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 배열 생성 함수

##### array
- 입력 데이터(리스트, 튜플, 배열 또는 다른 순차형 데이터)를 ndarray로 변환하며<br>
dtype을 명시하지 않은 경우 자료형을 추론해 저장. 
- 기본적으로 입력데이터는 복사됨

In [50]:
arr1 = np.array([[1,2],[3,4]])

In [51]:
arr2 = np.array([[5,6],[7,8]])

In [52]:
arr1

array([[1, 2],
       [3, 4]])

In [53]:
arr2

array([[5, 6],
       [7, 8]])

##### asarray
- 입력 데이터를 ndarray로 변환하지만 입력데이터가 이미 ndarray일 경우 복사가 일어나지 않음
- 이미 ndarray의 데이터 형태(data type)가 설정되어 있다면, 데이터 형태가 다를 경우메나 복사(copy)

In [39]:
#이미 존재하는 배열에 대해서는 복사 X
a = np.array([1,2,3])

In [40]:
np.asarray(a) is a

True

In [41]:
#만약 dtype이 설정되어 있다면,데이터 형태가 다를 경우에만 복사
b = np.array([1,2,3], dtype = np.float32)

In [42]:
#np.array는 데이터 형태 일치 여부에 상관없이 복사
np.array(b, dtype = np.float32) is b

False

In [43]:
#np.asarray
## 데이터 형태가 같을 때 복사하지 않음
np.asarray(b, dtype = np.float32) is b

True

In [44]:
# 데이터 형태가 다를 떼 복사
np.asarray(b, dtype = np.float64) is b

False

##### arange
- 내장 range 함수와 유사하지만 리스트 대신 ndarray 반환
- 맨 끝자리 숫자 포함 X

In [ ]:
a = np.arange(10)

In [45]:
np.arange(3)

array([0, 1, 2])

In [46]:
np.arange(3.0)

array([0., 1., 2.])

In [47]:
np.arange(3,7)

array([3, 4, 5, 6])

In [48]:
np.arange(3,7,2)

array([3, 5])

##### ones, ones_like
- 주어진 dtype과 모양을 가지는 배열을 생성하고 내용을 모두 1로 초기화.<br>
ones_like는 주어진 배열과 동일한 모양(형태)과 dtype(데이터타입)을 가지는 배열을 새로 생성해 내용을 모두 1로 초기화

In [54]:
a = np.ones((3,3), int)

In [55]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [56]:
a*3

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [57]:
a = np.arange(6).reshape(2,3)

In [58]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [60]:
b = np.arange(3, dtype=np.float)

C:\Users\user\AppData\Local\Temp\ipykernel_12752\1145467606.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = np.arange(3, dtype=np.float)


In [61]:
print(b)

[0. 1. 2.]


In [63]:
b.dtype

dtype('float64')

In [64]:
np.ones_like(b)

array([1., 1., 1.])

##### zeros, zeros_like 
- ones, ones_like와 동일하지만 내용을 0으로 채운다

In [72]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
b[2,0] = 3

In [74]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [3., 0., 0.]])

In [70]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [75]:
b = np.arange(3, dtype = np.float)
print(b)
b.dtype

[0. 1. 2.]


C:\Users\user\AppData\Local\Temp\ipykernel_12752\157655229.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = np.arange(3, dtype = np.float)


dtype('float64')

In [76]:
np.zeros_like(b)

array([0., 0., 0.])

##### empty, empty_like
- 메모리를 할당해 새로운 배열을 생성하지만 ones나 zeros처럼 값을 초기화하지 X

In [78]:
np.empty((2,3)) # null에 해당하는 주소값, 초기화 안함

array([[3.74657491, 1.82121925, 0.89657883],
       [1.44934464, 2.82412272, 0.51847576]])

In [80]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
np.empty_like(a)

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
b = np.arange(3, dtype = np.float)
print(b)
b.dtype

[0. 1. 2.]


C:\Users\user\AppData\Local\Temp\ipykernel_12752\157655229.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = np.arange(3, dtype = np.float)


dtype('float64')

In [83]:
np.empty_like(b)

array([0., 1., 2.])

##### full, full_like
- 인자로 받은 dtype과 배열의 모양을 가지는 배열을 생성하고 인자로 받은 값으로 배열을 채운다

In [84]:
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [86]:
np.full((4,3),2) # np.full(shape, fill_value)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [87]:
np.full_like(a)

TypeError: _full_like_dispatcher() missing 1 required positional argument: 'fill_value'

In [88]:
np.full_like(a,3)

array([[3, 3, 3],
       [3, 3, 3]])

In [89]:
np.full_like(b, 3.1)

array([3.1, 3.1, 3.1])

##### eye, identity
- N X N 크기의 단위행렬 생성(좌상단에서 우하단을 잇는 대각선은 1로 채워지고 나머지는 0으로 채워짐)

- np.identity()는 정사각행렬이 정해져 있다

In [93]:
d = np.identity(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [94]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- np.eye(4)와 np.identity(4)는 같다

In [95]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [90]:
d = np.eye(4,3)

In [91]:
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [92]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

***np.identity()와 np.eye()의 차이***
- identity 행렬은 항상 N x N의 행렬이라면, eye는 원하는 N x M의 행렬을 만들 수 있음

### 4.1.2 ndarray의 dtype
- dtype은 ndarray가 메모리에 있는 특정 데이터를 해석하기 위해 필요한 정보(또는 ***메타데이터***)를 담고 있는 특수한 객체

In [96]:
arr1 = np.array([1,2,3], dtype = np.float64)

In [97]:
arr2 = np.array([1,2,3], dtype = np.int32)

In [98]:
arr1.dtype

dtype('float64')

In [99]:
arr2.dtype

dtype('int32')

#### NumPy 자료형

|자료형|자료형 코드|설명|
|---|---|---|
|int8, uint8|i1,u1|부호가 있는 8비트(1바이트) 정수형과 부호가 없는 8비트 정수형|
|int16, uint16|i2, u2|부호가 있는 16비트 정수형과 부호가 없는 16비트 정수형|
|int32, uint32|i4, u4|부호가 있는 32비트 정수형과 부호가 없는 32비트 정수형|
|int64, uint64|i8, u8|부호가 있는 64비트 정수형과 부호가 없는 64비트 정수형|
|float16|f2|반정밀도 부동소수점|
|float32|f4 또는 f|단정밀도 부동소수점.C언어의 float형과 호환|
|float64|f8 또는 d|배정밀도 부동소수점.C언어의 double형과 파이썬의 float 객체와 호환|
|float128|f16 또는 g|확장정밀도 부동소수점|
|complex64,|c8, c16, c32|각각 2개의 32, 64, 128비트 부동소수점형을 가지는 복소수|
|complex128,|
|complex256|
|bool|?|True와 False 값을 저장하는 불리언형|
|object|0|파이썬 객체형|
|string_|S|고정 길이 아스키 문자열형(각 문자는 1바이트). 길이가 10인 문자열 dtype은 S10이 된다|
|unicode_|U|고정 길이 유니코드형(플랫폼에 따라 문자열 바이트 수가 다르다).string_형과 같은 형식을 쓴다(예:U10)|

ndarray의 astype 메서드를 사용해서 배열의 dtype을 다른 형으로 명시적 변환(또는 ***캐스팅***) 가능

In [100]:
arr = np.array([1,2,3,4,5])

In [101]:
arr.dtype

dtype('int32')

In [102]:
float_arr = arr.astype(np.float64)

In [103]:
float_arr.dtype

dtype('float64')

위 예제에서는 정수형을 부동소수점으로 변환함.<br>
만약 부동소수점수를 정수형 dtype으로 변환하면 소수점 아래 자리는 버려짐

In [104]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [105]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [106]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

숫자 형식의 문자열을 담고 있는 배열이 있다면 ***astype***을 이용해 숫자로 변환 가능

In [107]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [108]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

다른 배열의 dtype 속성을 이용하는 것도 가능

In [112]:
int_array = np.arange(10)

In [113]:
calibers = np.array([.22,.270,.357,.380,.44,.50], dtype = np.float64)

In [115]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

dtype으로 사용할 수 있는 축약 코드도 있다

In [116]:
empty_unit32 = np.empty(8, dtype='u4')

In [117]:
empty_unit32

array([         0, 1072693248,          0, 1072693248,          0,
       1072693248,          0, 1072693248], dtype=uint32)

***NOTE_*** astype을 호출하면 새로운 dtype이 이전 dtype과 동일해도 항상 새로운 배열을 생성(데이터를 복사)

### 4.1.3 NumPy 배열의 산술 연산

배열의 중요한 특징은 for문을 작성항지 않고 데이터를 일괄 처리할 수 있다는 것.이를 ***벡터화***라고 함<br>
같은 크기의 배열 간의 산술 연산은 배열의 각 원소 단위로 적용

In [118]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])

In [119]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [120]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [121]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

스칼라 인자가 포함된 산술 연산의 경우 배열 내의 모든 원소에 스칼라 인자가 적용됨

In [122]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [123]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

같은 크기를 가지는 배열 간의 비교 연산은 불리언 배열을 반환

In [125]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [126]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [127]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

***브로드캐스팅(broadcasting)*** : 크기가 다른 배열 간의 연산

### 4.1.4 색인과 슬라이싱 기초

In [128]:
arr = np.arange(10)

In [129]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
arr[5]

5

In [131]:
arr[5:8]

array([5, 6, 7])

In [132]:
arr[5:8] = 12

In [133]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

위에서 볼 수 있듯이 arr[5:8] = 12처럼 배열 조각에 스칼라값을 대입하면 12가 선택 영역 전체로 전파(또는 ***브로드캐스팅)됨.<br>
리스트와의 중요한 차이점은 배열 조각은 원본 배열의 ***뷰***라는 점<br>
즉, 데이터는 복사되지 않고 뷰에 대한  변경은 그대로 원본 배열에 반영됨

이에 대한 예제로 먼저 arr 배열의 슬라이스를 생성해보자

In [134]:
arr_slice = arr[5:8]

In [135]:
arr_slice

array([12, 12, 12])

그리고 arr_slice의 값은 변경하면 원래 배열인 arr의 값도 바뀐다

In [136]:
arr_slice[1] = 12345

In [137]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

단순히 [:]로 슬라이스를 하면 배열의 모든 값을 할당

In [138]:
arr_slice[:] = 64

In [139]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

***CAUTION_*** 만약 뷰 대신 ndarray 슬라이스의 복사본을 얻고 싶다면 arr[5:8].copy()를 사용해 명시적으로 배열 복사

다차원 배열을 다룰 때는 좀 더 많은 옵션이 있다. <br>
2차원 배열에서 각 색인에 해당하는 요소는 스칼라값이 아니라 1차원 배열

In [140]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [142]:
arr2d[2]

array([7, 8, 9])

따라서 개별 요소는 재귀적으로 접근해야 함<br>
하지만 그렇게 하기는 귀찮기 때문에 콤마로 구분된 색인 리스트를 넘기면 됨. <br>
그러므로 다음 두 표현은 동일

In [143]:
arr2d[0][2]

3

In [144]:
arr2d[0,2]

3

다차원 배열에서 마지막 색인을 생략하면 반환되는 객체는 상위 차원의 데이터를 포함하고 있는 한 차원 낮은 ndarray가 됨<br>
2x2x3 크기의 배열 arr3d가 있다면

In [145]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [146]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

arr3d[0]은 2x3 크기의 배열

In [147]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

arr3d[0]에는 스칼라값과 배열 모두 대입 가능

In [148]:
old_values = arr3d[0].copy()

In [149]:
arr3d[0] = 42

In [150]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [151]:
arr3d[0] = old_values

In [152]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

이런 식으로 arr3d[1,0]은 색인되는 1차원 배열과 그 값을 반환

In [153]:
arr3d[1,0]

array([7, 8, 9])

이 표현은 다음처럼 두 번에 걸쳐 인덱싱한 결과와 동일

In [154]:
x = arr3d[1]

In [155]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [156]:
x[0]

array([7, 8, 9])

여기서 살펴본 선택된 배열의 부분집합은 모두 배열의 뷰를 반환

#### 슬라이스로 선택하기

파이썬의 리스트 같은 1차원 객체처럼 ndarray는 익숙한 문법으로 슬라이싱 가능

In [157]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [158]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

위에서 살펴본 arr2d를 생각해보자. 이 배열을 슬라이싱하는 방법은 조금 다르다.

In [159]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

확인한 것처럼 첫 번째 축인 0번 축을 기준으로 슬라이싱됨.<br>
따라서 슬라이스는 축을 따라 선택 영역 내의 요소를 선택<br>
arr2d[:2]는 'arr2d의 시작부터 두 번째 로우까지의 선택'이라고 이해하면 쉽다

색인을 여러개 넘겨서 다차원을 슬라이싱하는 것도 가능

In [161]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

이렇게 슬라이싱하면 항상 같은 차원의 배열에 대한 뷰를 얻게 됨<br>
정수 색인과 슬라이스를 함께 사용해 한 차원 낮은 슬라이스를 얻을 수 있음

예를 들어 두 번째 로우에서 처음 두 컬럼만 선택하고 싶다면 아래처럼 하면 됨

In [162]:
arr2d[1,:2]

array([4, 5])

이와 유사하게 처음 두 로우에서 세 번째 컬럼만 선택하고 싶다면 아래처럼 하면 된다

In [163]:
arr2d[:2, 2]

array([3, 6])

In [164]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

물론 슬라이싱 구문에 값을 대입하면 선택 영역 전체에 값이 대입됨

In [165]:
arr2d[:2, 1:] = 0

In [166]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 4.1.5 불리언값으로 선택하기

중복된 이름이 포함된 배열이 있다고 하자. 그리고 numpy.random 모듈에 있는 randn 함수를 사용해서 임의의 표준 정규 분포 데이터를 생성하자.

In [167]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [168]:
data = np.random.randn(7,4)

***np.random.rand(p,q)***
- 0부터 1사이 균일 분포 난수를 matrix array(p,q)로 생성

In [169]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [170]:
data

array([[ 0.18951032,  1.21690048,  0.63734159, -1.06046974],
       [ 0.356682  ,  1.14872329, -0.28776413,  1.46140407],
       [ 0.21383922, -0.32892646, -1.68079194, -0.4015384 ],
       [-1.59320341, -1.29902275, -0.64484517,  0.5160515 ],
       [ 0.9041314 ,  0.473549  , -0.05508576, -1.12919222],
       [-0.6558659 , -0.14091587,  0.18223913, -0.83400118],
       [ 0.77100014,  0.45772997,  0.37869548, -1.04222926]])

각각의 이름은 data 배열의 각 로우에 대응한다고 가정.<br>
만약 전체 로우에서 'Bob'과 같은 이름을 선택하려면 산술 연산자 마찬가지로 배열에 대한 비교 연산(== 같은)도 벡터화되므로<br>
names를 'Bob' 문자열과 비교하면 불리언 배열을 반환

In [171]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

이 불리언 배열은 배열의 색인으로 사용 가능

In [172]:
data[names == 'Bob']

array([[ 0.18951032,  1.21690048,  0.63734159, -1.06046974],
       [-1.59320341, -1.29902275, -0.64484517,  0.5160515 ]])

불리언 배열은 반드시 색인하려는 축의 길이와 동일한 길이를 가져야 함.<br>
불리언 배열 색인도 슬라이스나 요소를 선택하는데 짜 맞출 수 있음