# 복습

In [2]:
import numpy as np
a = np.array([[2,1,6],[0,7,4],[5,3,2]])

In [3]:
np.sort(a, axis=0)

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [7]:
a = np.array([0,1,2,3,4,5])
b = np.array([[0],[10],[20],[30],[40],[50]])
a = a+b

In [8]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [9]:
#홀수만?
a[:, 1::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25],
       [31, 33, 35],
       [41, 43, 45],
       [51, 53, 55]])

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame([['cat', 'mango'],['dog','orange'],['lion','melon']],
                 columns=['animal','fruit'])

In [15]:
df

animal   fruit
0    cat   mango
1    dog  orange
2   lion   melon

- mango랑 melon 추출

In [34]:
df.loc[:, 'fruit'][[0,2]]
df.loc[:, 'fruit'][::2]

0    mango
2    melon
Name: fruit, dtype: object

In [35]:
df.iloc[:, 1][[0,2]]

0    mango
2    melon
Name: fruit, dtype: object

In [40]:
df['fruit'][[0,2]]
df.fruit[[0,2]]

0    mango
2    melon
Name: fruit, dtype: object

In [46]:
df[::2]

animal  fruit
0    cat  mango
2   lion  melon

In [47]:
df = pd.DataFrame([['John',25,'student'],['Cho',30,'teacher']],
                           columns= ['Name','Age','Job']) 

In [48]:
df

Name  Age      Job
0  John   25  student
1   Cho   30  teacher

- name과 job열 뽑기

In [52]:
df.iloc[:,::2]

Name      Job
0  John  student
1   Cho  teacher

In [53]:
a = np.array([[3,5,1],[2,4,6]])
a 

array([[3, 5, 1],
       [2, 4, 6]])

In [54]:
np.min(a)

1

In [55]:
np.argmin(a)

2

In [62]:
import random
a = random.sample(range(25), 25)
np.array(a).reshape(5,5)
# a.reshape(5,5)

array([[24, 22,  3, 20, 23],
       [ 5,  1,  4, 14,  8],
       [ 0, 16,  7, 19, 17],
       [ 6,  2, 12, 11, 13],
       [10, 21, 18, 15,  9]])

In [65]:
np.array(random.sample(range(25), k=25)).reshape(5,5) 

array([[20, 24, 21, 13,  7],
       [10,  5, 18,  2,  8],
       [ 0, 23, 15,  9, 16],
       [ 3, 14,  6,  1, 22],
       [17,  4, 12, 11, 19]])

In [66]:
np.random.randint(0,25, size = (5,5))

array([[ 8,  7, 21, 14,  6],
       [20,  8,  3,  4, 20],
       [19, 16,  1, 11,  8],
       [ 6,  7, 21,  1, 12],
       [ 8,  9, 10,  6, 16]])

In [69]:
np.random.random(3)
np.random.rand(3)
#random은 rand와 같다

array([0.48690411, 0.20216288, 0.81960239])

In [70]:
random.random()

0.03075342496787581

In [73]:
np.random.permutation(25).reshape(5,5) #무작위로 섞은 배열 만듦

array([[15,  9,  8, 23, 12],
       [ 1, 16,  5, 22, 13],
       [ 2, 10,  7, 19,  4],
       [18,  0,  6, 17, 20],
       [ 3, 21, 14, 24, 11]])

In [79]:
li =list(range(25))
random.shuffle(li)
np.array(li).reshape(5,5)

array([[16,  3,  6, 14, 20],
       [10, 15, 21,  8,  7],
       [23, 19,  2, 24, 22],
       [ 0,  1,  5, 11, 18],
       [ 4, 12, 17, 13,  9]])

In [78]:
li

[7,
 8,
 23,
 1,
 9,
 10,
 4,
 0,
 5,
 19,
 2,
 6,
 15,
 18,
 13,
 24,
 12,
 21,
 20,
 16,
 11,
 3,
 17,
 22,
 14]

In [85]:
random.seed(1234)
a = np.array(random.sample(li,k=25)).reshape(5,5)
a 

array([[ 9, 22, 14, 16,  6],
       [11,  3,  4, 17, 19],
       [ 1, 12, 24,  2, 10],
       [ 7, 21,  8, 18,  0],
       [15, 23, 13, 20,  5]])

In [87]:
np.max(a)

24

In [89]:
np.max(a,axis=1)

array([22, 19, 24, 21, 23])

In [109]:
df = pd.DataFrame([[90,98,95,100],[80,89,95,90],[60,65,80,90]],
                 index=['서준','우현','인아'],
                 columns=['수학','영어','음악','체육'])
df 

수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90
인아  60  65  80   90

In [112]:
df.loc[["서준"]]
df.iloc[0]
df.iloc[[0], :]
df.iloc[0, :]
df[:1] = 0
df

수학  영어  음악  체육
서준   0   0   0   0
우현  80  89  95  90
인아  60  65  80  90

In [113]:
df.iloc[0, :] = 0
df

수학  영어  음악  체육
서준   0   0   0   0
우현  80  89  95  90
인아  60  65  80  90

In [137]:
import plotly.express as px
df= px.data.gapminder() 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    1704 non-null   object 
 1   continent  1704 non-null   object 
 2   year       1704 non-null   int64  
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64  
 5   gdpPercap  1704 non-null   float64
 6   iso_alpha  1704 non-null   object 
 7   iso_num    1704 non-null   int64  
dtypes: float64(2), int64(3), object(3)
memory usage: 106.6+ KB


In [117]:
# object는 글자를 의미

In [119]:
df[:2]

country continent  year  lifeExp      pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801  8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332  9240934  820.853030       AFG   

   iso_num  
0        4  
1        4

In [124]:
#country와 continent 정보만 

In [127]:
df[['country', 'continent']]

country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
1699     Zimbabwe    Africa
1700     Zimbabwe    Africa
1701     Zimbabwe    Africa
1702     Zimbabwe    Africa
1703     Zimbabwe    Africa

[1704 rows x 2 columns]

In [125]:
df.iloc[:,:2]

country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
1699     Zimbabwe    Africa
1700     Zimbabwe    Africa
1701     Zimbabwe    Africa
1702     Zimbabwe    Africa
1703     Zimbabwe    Africa

[1704 rows x 2 columns]

In [130]:
#이름을 '나라', '대륙'으로 수정

In [129]:
df.rename(columns = {"country":'나라', "continent":'대륙'})

나라      대륙  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan    Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan    Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan    Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan    Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan    Asia  1972   36.088  13079460  739.981106       AFG   
...           ...     ...   ...      ...       ...         ...       ...   
1699     Zimbabwe  Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe  Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe  Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe  Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe  Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [138]:
df

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [134]:
df = df.drop(['gdpPercap', 'iso_alpha', 'iso_num'], axis=1)

In [135]:
df

country continent  year  lifeExp       pop
0     Afghanistan      Asia  1952   28.801   8425333
1     Afghanistan      Asia  1957   30.332   9240934
2     Afghanistan      Asia  1962   31.997  10267083
3     Afghanistan      Asia  1967   34.020  11537966
4     Afghanistan      Asia  1972   36.088  13079460
...           ...       ...   ...      ...       ...
1699     Zimbabwe    Africa  1987   62.351   9216418
1700     Zimbabwe    Africa  1992   60.377  10704340
1701     Zimbabwe    Africa  1997   46.809  11404948
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[1704 rows x 5 columns]

In [ ]:
df.iloc[:, :-3]

In [142]:
#2002년(포함)부터 이후의 데이터만

In [145]:
df[df.year>=2002]

country continent  year  lifeExp       pop    gdpPercap iso_alpha  \
10    Afghanistan      Asia  2002   42.129  25268405   726.734055       AFG   
11    Afghanistan      Asia  2007   43.828  31889923   974.580338       AFG   
22        Albania    Europe  2002   75.651   3508512  4604.211737       ALB   
23        Albania    Europe  2007   76.423   3600523  5937.029526       ALB   
34        Algeria    Africa  2002   70.994  31287142  5288.040382       DZA   
...           ...       ...   ...      ...       ...          ...       ...   
1679  Yemen, Rep.      Asia  2007   62.698  22211743  2280.769906       YEM   
1690       Zambia    Africa  2002   39.193  10595811  1071.613938       ZMB   
1691       Zambia    Africa  2007   42.384  11746035  1271.211593       ZMB   
1702     Zimbabwe    Africa  2002   39.989  11926563   672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143   469.709298       ZWE   

      iso_num  
10          4  
11          4  
22          8  
23          8  
34         12  
...       ...  
1679      887  
1690      894  
1691      894  
1702      716  
1703      716  

[284 rows x 8 columns]

In [151]:
df= pd.DataFrame([[20,'AB', '서울'], [25,'B', '강원'], [27, 'A', '경기']],
                index=['길동', '춘향', '몽룡'],
                columns = ['이름', '혈액형', '거주지'])

In [152]:
df

이름 혈액형 거주지
길동  20  AB  서울
춘향  25   B  강원
몽룡  27   A  경기

In [153]:
df.drop('길동')

이름 혈액형 거주지
춘향  25   B  강원
몽룡  27   A  경기

In [155]:
df = df.rename(columns = {'거주지':'출생지'})
df

이름 혈액형 출생지
길동  20  AB  서울
춘향  25   B  강원
몽룡  27   A  경기

In [168]:
df = pd.DataFrame([[90,98,95,100],[80,89,95,90],[60,65,80,90]],
                 index=['서준','우현','인아'],
                 columns=['수학','영어','음악','체육'])
df 

수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90
인아  60  65  80   90

In [158]:
df.loc['인아'] = [95,100,80,95]

In [159]:
df

수학   영어  음악   체육
서준  90   98  95  100
우현  80   89  95   90
인아  95  100  80   95

In [173]:
df['과학'] = [80]
df

ValueError: Length of values (1) does not match length of index (3)

In [ ]:
d[2,3] #pandas는 numpy가 아니다
dfiloc[2,3]
df.iloc[2][3]

In [169]:
df.loc["인아",["체육", "영어"]] = 80,90

In [171]:
df

수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90
인아  60  90  80   80

In [175]:
df.loc['인아',['체육', '영어']] = 80,90

In [181]:
with open("...txt", "w") as f:
    f.write("Hello")
    
with open("...txt", "r") as f:
    lines = f.readlines()
    for line in lines:
        print(line.strip())

Hello


In [219]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv') #깃허브 raw 링크 복사
df
# 1. displacement -> displ
# 2. model-year ->year
# 3. year 75이상인 것만 뽑는다.
# 4. year 칼럼

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [201]:
df.to_csv("mpg.csv") #저장

In [202]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [203]:
df = df.rename(columns = {'displacement':'displ', 'model-year':'year'})

In [204]:
df

mpg  cylinders  displ  horsepower  weight  acceleration  year
0    18.0          8  307.0       130.0    3504          12.0    70
1    15.0          8  350.0       165.0    3693          11.5    70
2    18.0          8  318.0       150.0    3436          11.0    70
3    16.0          8  304.0       150.0    3433          12.0    70
4    17.0          8  302.0       140.0    3449          10.5    70
..    ...        ...    ...         ...     ...           ...   ...
393  27.0          4  140.0        86.0    2790          15.6    82
394  44.0          4   97.0        52.0    2130          24.6    82
395  32.0          4  135.0        84.0    2295          11.6    82
396  28.0          4  120.0        79.0    2625          18.6    82
397  31.0          4  119.0        82.0    2720          19.4    82

[398 rows x 7 columns]

In [205]:
df = df[df.year>=75]

In [206]:
df

mpg  cylinders  displ  horsepower  weight  acceleration  year
152  19.0          6  225.0        95.0    3264          16.0    75
153  18.0          6  250.0       105.0    3459          16.0    75
154  15.0          6  250.0        72.0    3432          21.0    75
155  15.0          6  250.0        72.0    3158          19.5    75
156  16.0          8  400.0       170.0    4668          11.5    75
..    ...        ...    ...         ...     ...           ...   ...
393  27.0          4  140.0        86.0    2790          15.6    82
394  44.0          4   97.0        52.0    2130          24.6    82
395  32.0          4  135.0        84.0    2295          11.6    82
396  28.0          4  120.0        79.0    2625          18.6    82
397  31.0          4  119.0        82.0    2720          19.4    82

[246 rows x 7 columns]

In [207]:
df['year'] += 1900
df

C:\Users\user\AppData\Local\Temp\ipykernel_5668\1603560223.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] += 1900


mpg  cylinders  displ  horsepower  weight  acceleration  year
152  19.0          6  225.0        95.0    3264          16.0  1975
153  18.0          6  250.0       105.0    3459          16.0  1975
154  15.0          6  250.0        72.0    3432          21.0  1975
155  15.0          6  250.0        72.0    3158          19.5  1975
156  16.0          8  400.0       170.0    4668          11.5  1975
..    ...        ...    ...         ...     ...           ...   ...
393  27.0          4  140.0        86.0    2790          15.6  1982
394  44.0          4   97.0        52.0    2130          24.6  1982
395  32.0          4  135.0        84.0    2295          11.6  1982
396  28.0          4  120.0        79.0    2625          18.6  1982
397  31.0          4  119.0        82.0    2720          19.4  1982

[246 rows x 7 columns]

In [212]:
df.to_csv("mpg.csv")

In [213]:
pd.read_clipboard()

Empty DataFrame
Columns: [df.to_csv("mpg.csv")]
Index: []

In [214]:
import os
os.getcwd()

'C:\\Users\\user\\dataanalysis'

In [217]:
pd.read_excel("./Downloads/Presidents.xlsx")
df.to_csv("test.csv")
df.to_excell("test.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: './Downloads/Presidents.xlsx'

In [ ]:
pd.read_clipboard()

In [220]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [221]:
df.head(2)

mpg  cylinders  displacement  horsepower  weight  acceleration  model-year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70

In [222]:
df.tail(2)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
396          82  
397          82

In [223]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  396.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.189394  2970.424623   
std      7.815984    1.701004    104.269838   38.402030   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   92.000000  2803.500000   
75%     29.000000    8.000000    262.000000  125.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model-year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

In [224]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    396 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model-year    398 non-null    int64  
dtypes: float64(4), int64(3)
memory usage: 21.9 KB


In [225]:
df.shape

(398, 7)

In [227]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model-year        int64
dtype: object

In [228]:
df.count()

mpg             398
cylinders       398
displacement    398
horsepower      396
weight          398
acceleration    398
model-year      398
dtype: int64

In [230]:
df['cylinders']
df['cylinders'].count()

398

In [231]:
df['cylinders'].value_counts()

4    204
8    103
6     84
3      4
5      3
Name: cylinders, dtype: int64

In [232]:
df['cylinders']

0      8
1      8
2      8
3      8
4      8
      ..
393    4
394    4
395    4
396    4
397    4
Name: cylinders, Length: 398, dtype: int64

In [233]:
df.value_counts()

mpg   cylinders  displacement  horsepower  weight  acceleration  model-year
9.0   8          304.0         193.0       4732    18.5          70            1
27.2  4          119.0         97.0        2300    14.7          78            1
27.0  4          151.0         90.0        2735    18.0          82            1
                 140.0         86.0        2790    15.6          82            1
                 112.0         88.0        2640    18.6          82            1
                                                                              ..
18.5  8          360.0         150.0       3940    13.0          79            1
      6          250.0         110.0       3645    16.2          76            1
                               98.0        3525    19.0          77            1
18.2  8          318.0         135.0       3830    15.2          79            1
46.6  4          86.0          65.0        2110    17.9          80            1
Length: 396, dtype: int64

In [234]:
df.value_counts()

mpg   cylinders  displacement  horsepower  weight  acceleration  model-year
9.0   8          304.0         193.0       4732    18.5          70            1
27.2  4          119.0         97.0        2300    14.7          78            1
27.0  4          151.0         90.0        2735    18.0          82            1
                 140.0         86.0        2790    15.6          82            1
                 112.0         88.0        2640    18.6          82            1
                                                                              ..
18.5  8          360.0         150.0       3940    13.0          79            1
      6          250.0         110.0       3645    16.2          76            1
                               98.0        3525    19.0          77            1
18.2  8          318.0         135.0       3830    15.2          79            1
46.6  4          86.0          65.0        2110    17.9          80            1
Length: 396, dtype: int64

In [235]:
df['cylinders'].unique()

array([8, 4, 6, 3, 5], dtype=int64)

In [236]:
df.value_counts()

mpg   cylinders  displacement  horsepower  weight  acceleration  model-year
9.0   8          304.0         193.0       4732    18.5          70            1
27.2  4          119.0         97.0        2300    14.7          78            1
27.0  4          151.0         90.0        2735    18.0          82            1
                 140.0         86.0        2790    15.6          82            1
                 112.0         88.0        2640    18.6          82            1
                                                                              ..
18.5  8          360.0         150.0       3940    13.0          79            1
      6          250.0         110.0       3645    16.2          76            1
                               98.0        3525    19.0          77            1
18.2  8          318.0         135.0       3830    15.2          79            1
46.6  4          86.0          65.0        2110    17.9          80            1
Length: 396, dtype: int64

In [237]:
df.mean() #칼럼별로 mean

mpg               23.514573
cylinders          5.454774
displacement     193.425879
horsepower       104.189394
weight          2970.424623
acceleration      15.568090
model-year        76.010050
dtype: float64

In [239]:
df['mpg'].mean()

23.514572864321607

In [240]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [242]:
df.mean() #함수가 아니라 메서드

mpg               23.514573
cylinders          5.454774
displacement     193.425879
horsepower       104.189394
weight          2970.424623
acceleration      15.568090
model-year        76.010050
dtype: float64

In [243]:
np.mean(df)

C:\Users\user\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


mpg               23.514573
cylinders          5.454774
displacement     193.425879
horsepower       104.189394
weight          2970.424623
acceleration      15.568090
model-year        76.010050
dtype: float64

In [245]:
np.mean(df, axis=1)

0      578.428571
1      616.071429
2      573.000000
3      570.428571
4      570.928571
          ...    
393    449.228571
394    347.657143
395    377.657143
396    422.371429
397    436.771429
Length: 398, dtype: float64

In [247]:
df.values

array([[  18. ,    8. ,  307. , ..., 3504. ,   12. ,   70. ],
       [  15. ,    8. ,  350. , ..., 3693. ,   11.5,   70. ],
       [  18. ,    8. ,  318. , ..., 3436. ,   11. ,   70. ],
       ...,
       [  32. ,    4. ,  135. , ..., 2295. ,   11.6,   82. ],
       [  28. ,    4. ,  120. , ..., 2625. ,   18.6,   82. ],
       [  31. ,    4. ,  119. , ..., 2720. ,   19.4,   82. ]])

In [248]:
df.corr()

mpg  cylinders  displacement  horsepower    weight  \
mpg           1.000000  -0.775396     -0.804203   -0.777575 -0.831741   
cylinders    -0.775396   1.000000      0.950721    0.843751  0.896017   
displacement -0.804203   0.950721      1.000000    0.897787  0.932824   
horsepower   -0.777575   0.843751      0.897787    1.000000  0.864350   
weight       -0.831741   0.896017      0.932824    0.864350  1.000000   
acceleration  0.420289  -0.505419     -0.543684   -0.687241 -0.417457   
model-year    0.579267  -0.348746     -0.370164   -0.420697 -0.306564   

              acceleration  model-year  
mpg               0.420289    0.579267  
cylinders        -0.505419   -0.348746  
displacement     -0.543684   -0.370164  
horsepower       -0.687241   -0.420697  
weight           -0.417457   -0.306564  
acceleration      1.000000    0.288137  
model-year        0.288137    1.000000

In [249]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [250]:
df.corr()

mpg  cylinders  displacement  horsepower    weight  \
mpg           1.000000  -0.775396     -0.804203   -0.777575 -0.831741   
cylinders    -0.775396   1.000000      0.950721    0.843751  0.896017   
displacement -0.804203   0.950721      1.000000    0.897787  0.932824   
horsepower   -0.777575   0.843751      0.897787    1.000000  0.864350   
weight       -0.831741   0.896017      0.932824    0.864350  1.000000   
acceleration  0.420289  -0.505419     -0.543684   -0.687241 -0.417457   
model-year    0.579267  -0.348746     -0.370164   -0.420697 -0.306564   

              acceleration  model-year  
mpg               0.420289    0.579267  
cylinders        -0.505419   -0.348746  
displacement     -0.543684   -0.370164  
horsepower       -0.687241   -0.420697  
weight           -0.417457   -0.306564  
acceleration      1.000000    0.288137  
model-year        0.288137    1.000000

In [251]:
titanic = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [252]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [254]:
titanic.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [255]:
df.isnull()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    False      False         False       False   False         False   
1    False      False         False       False   False         False   
2    False      False         False       False   False         False   
3    False      False         False       False   False         False   
4    False      False         False       False   False         False   
..     ...        ...           ...         ...     ...           ...   
393  False      False         False       False   False         False   
394  False      False         False       False   False         False   
395  False      False         False       False   False         False   
396  False      False         False       False   False         False   
397  False      False         False       False   False         False   

     model-year  
0         False  
1         False  
2         False  
3         False  
4         False  
..          ...  
393       False  
394       False  
395       False  
396       False  
397       False  

[398 rows x 7 columns]

In [256]:
df.isnull()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    False      False         False       False   False         False   
1    False      False         False       False   False         False   
2    False      False         False       False   False         False   
3    False      False         False       False   False         False   
4    False      False         False       False   False         False   
..     ...        ...           ...         ...     ...           ...   
393  False      False         False       False   False         False   
394  False      False         False       False   False         False   
395  False      False         False       False   False         False   
396  False      False         False       False   False         False   
397  False      False         False       False   False         False   

     model-year  
0         False  
1         False  
2         False  
3         False  
4         False  
..          ...  
393       False  
394       False  
395       False  
396       False  
397       False  

[398 rows x 7 columns]

In [257]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      2
weight          0
acceleration    0
model-year      0
dtype: int64

In [259]:
df = titanic.copy()
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [260]:
df1 = df.copy()

In [261]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [265]:
df.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  183 non-null    int64  
 1   Survived     183 non-null    int64  
 2   Pclass       183 non-null    int64  
 3   Name         183 non-null    object 
 4   Sex          183 non-null    object 
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64  
 7   Parch        183 non-null    int64  
 8   Ticket       183 non-null    object 
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object 
 11  Embarked     183 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB


In [267]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [270]:
df.dropna(axis=1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
dtypes: float64(1), int64(5), object(3)
memory usage: 62.8+ KB


In [272]:
mean_age = df['Age'].mean()
df['Age'].fillna(mean_age, inplace=True)

In [274]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [276]:
df['Age'].isnull().sum()

0

In [277]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [ ]:
merge(),join(), concat()

In [278]:
E = pd.Series(['e0','e1','e2','e3' ], name = 'e')
F = pd.Series(['f0','f1','f2'], name = 'f', index = [3,4,5])
G = pd.Series(['g0','g1','g2', 'g3'], name = 'g')

In [279]:
E

0    e0
1    e1
2    e2
3    e3
Name: e, dtype: object

In [280]:
F

3    f0
4    f1
5    f2
Name: f, dtype: object

In [281]:
G

0    g0
1    g1
2    g2
3    g3
Name: g, dtype: object

In [282]:
pd.concat([E, F])

0    e0
1    e1
2    e2
3    e3
3    f0
4    f1
5    f2
dtype: object

In [283]:
pd.concat([E, G])

0    e0
1    e1
2    e2
3    e3
0    g0
1    g1
2    g2
3    g3
dtype: object

In [284]:
pd.concat([E, F], axis = 1)

e    f
0   e0  NaN
1   e1  NaN
2   e2  NaN
3   e3   f0
4  NaN   f1
5  NaN   f2

In [285]:
pd.concat([E, G])

0    e0
1    e1
2    e2
3    e3
0    g0
1    g1
2    g2
3    g3
dtype: object

In [286]:
pd.concat([E, G], axis =1)

e   g
0  e0  g0
1  e1  g1
2  e2  g2
3  e3  g3

In [313]:
d1 = {'a': ['a0', 'a1', 'a2'],
      'b': ['b0', 'b1', 'b2'],
      'c': ['c0', 'c1', 'c2']}
d2 = {'b': ['b2', 'b3', 'b4'],
      'c': ['c2', 'c3', 'c4'],
      'd': ['d2', 'd3', 'd4']}

df1 = pd.DataFrame(d1, index = [0,1,2])
df2 = pd.DataFrame(d2, index = [1,2,3])

In [314]:
df1

a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2

In [315]:
df2

b   c   d
1  b2  c2  d2
2  b3  c3  d3
3  b4  c4  d4

In [316]:
pd.concat([df1, df2])

a   b   c    d
0   a0  b0  c0  NaN
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
1  NaN  b2  c2   d2
2  NaN  b3  c3   d3
3  NaN  b4  c4   d4

In [319]:
pd.concat([df1, df2], axis=1, join='inner')

a   b   c   b   c   d
1  a1  b1  c1  b2  c2  d2
2  a2  b2  c2  b3  c3  d3

In [352]:
titanic = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [332]:
for i in titanic.columns:
    titanic = titanic.rename(columns = {i:i.lower()})


In [333]:
titanic

passengerid  survived  pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  name     sex   age  sibsp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     parch            ticket     fare cabin embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
titanic 컬럼명들 소문자로 바꾸기

In [325]:
for i in titanic.columns:
    print(i)

PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked


In [346]:
titanic.columns = [i.lower() for i in titanic.columns] 

In [347]:
titanic.columns = map(lambda x: x.lower(), list(titanic.columns))

In [348]:
new_columns = []
for column in titanic.columns:
    new_columns.append(column.lower())
titanic.columns = new_columns 

In [349]:
titanic.columns.str.lower()

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [353]:
titanic['Name'].str.split('.')

0                             [Braund, Mr,  Owen Harris]
1      [Cumings, Mrs,  John Bradley (Florence Briggs ...
2                              [Heikkinen, Miss,  Laina]
3        [Futrelle, Mrs,  Jacques Heath (Lily May Peel)]
4                            [Allen, Mr,  William Henry]
                             ...                        
886                             [Montvila, Rev,  Juozas]
887                      [Graham, Miss,  Margaret Edith]
888          [Johnston, Miss,  Catherine Helen "Carrie"]
889                             [Behr, Mr,  Karl Howell]
890                               [Dooley, Mr,  Patrick]
Name: Name, Length: 891, dtype: object

In [354]:
titanic['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...                        
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: object

In [360]:
titanic[titanic['Name'].str.contains("^F.+")]

PassengerId  Survived  Pclass  \
3              4         1       1   
20            21         0       2   
27            28         0       1   
53            54         1       2   
86            87         0       3   
88            89         1       1   
137          138         0       1   
147          148         0       3   
228          229         0       2   
306          307         1       1   
309          310         1       1   
334          335         1       1   
341          342         1       1   
344          345         0       2   
357          358         0       2   
428          429         0       3   
436          437         0       3   
438          439         0       1   
452          453         0       1   
481          482         0       2   
525          526         0       3   
527          528         0       1   
539          540         1       1   
572          573         1       1   
587          588         1       1   
643          644         1       3   
660          661         1       1   
688          689         0       3   
736          737         0       3   
815          816         0       1   
825          826         0       3   

                                                  Name     Sex   Age  SibSp  \
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
20                                Fynney, Mr. Joseph J    male  35.0      0   
27                      Fortune, Mr. Charles Alexander    male  19.0      3   
53   Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.0      1   
86                              Ford, Mr. William Neal    male  16.0      1   
88                          Fortune, Miss. Mabel Helen  female  23.0      3   
137                        Futrelle, Mr. Jacques Heath    male  37.0      1   
147                   Ford, Miss. Robina Maggie "Ruby"  female   9.0      2   
228                          Fahlstrom, Mr. Arne Jonas    male  18.0      0   
306                            Fleming, Miss. Margaret  female   NaN      0   
309                     Francatelli, Miss. Laura Mabel  female  30.0      0   
334  Frauenthal, Mrs. Henry William (Clara Heinshei...  female   NaN      1   
341                     Fortune, Miss. Alice Elizabeth  female  24.0      3   
344                            Fox, Mr. Stanley Hubert    male  36.0      0   
357                          Funk, Miss. Annie Clemmer  female  38.0      0   
428                                   Flynn, Mr. James    male   NaN      0   
436               Ford, Miss. Doolina Margaret "Daisy"  female  21.0      2   
438                                  Fortune, Mr. Mark    male  64.0      1   
452                    Foreman, Mr. Benjamin Laventall    male  30.0      0   
481                   Frost, Mr. Anthony Wood "Archie"    male   NaN      0   
525                                 Farrell, Mr. James    male  40.5      0   
527                                 Farthing, Mr. John    male   NaN      0   
539                 Frolicher, Miss. Hedwig Margaritha  female  22.0      0   
572                   Flynn, Mr. John Irwin ("Irving")    male  36.0      0   
587                   Frolicher-Stehli, Mr. Maxmillian    male  60.0      1   
643                                    Foo, Mr. Choong    male   NaN      0   
660                      Frauenthal, Dr. Henry William    male  50.0      2   
688                    Fischer, Mr. Eberhard Thelander    male  18.0      0   
736            Ford, Mrs. Edward (Margaret Ann Watson)  female  48.0      1   
815                                   Fry, Mr. Richard    male   NaN      0   
825                                    Flynn, Mr. John    male   NaN      0   

     Parch      Ticket      Fare        Cabin Embarked  
3        0      113803   53.1000         C123        S  
20       0      239865   26.0000          NaN        S  
27       2       19950  263.0000  C23 C25 C27        S  
53       0        2926   26.000

In [6]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
              ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]
all_data 

[['John', 'Emily', 'Michael', 'Mary', 'Steven'],
 ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

In [7]:
#하나의 리스트에 담기 : names = []

In [8]:
all_data[0]

['John', 'Emily', 'Michael', 'Mary', 'Steven']

In [9]:
names = []

In [10]:
names = all_data[0]+all_data[1] 

In [11]:
for i in names:
    if i.count('e') == 2:
        print(i) 

Steven


In [14]:
import numpy as np
np.random.randn(2,3)

array([[ 0.5936841 ,  0.38459191,  0.385912  ],
       [-1.25373221,  0.29944194, -0.80287838]])

In [15]:
np.random.randn(2,3)

array([[-0.33418765, -0.25021124,  1.48511516],
       [ 0.70866474,  0.21405705,  1.31375216]])

In [16]:
np.random.randn(2,3)*3 + 80

array([[82.5557747 , 81.34854383, 83.26029573],
       [80.15650643, 78.43621074, 76.40744261]])

In [18]:
np.random.rand(2,3)

array([[0.22361904, 0.95052796, 0.53701161],
       [0.25764961, 0.14242412, 0.72932027]])

In [22]:
df['Pclass'] = df['Pclass'].astype("str")
df.info()

NameError: name 'df' is not defined