# 복습

In [11]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [18]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
#array([ 1,  7, 13, 19, 25])
np.diag(a)

array([ 1,  7, 13, 19, 25])

In [23]:
# array([ 2,  8, 14, 20])
np.diag(a,k=1)

array([ 2,  8, 14, 20])

In [27]:
np.array([10,12,15,25,28,30,35,42,50]) 
#1달러 = 1290원

array([10, 12, 15, 25, 28, 30, 35, 42, 50])

In [28]:
np.array([10,12,15,25,28,30,35,42,50]) *1290

array([12900, 15480, 19350, 32250, 36120, 38700, 45150, 54180, 64500])

In [29]:
np.array([10,12,15]) *np.array([10])
np.array([10,12,15]) *np.array([20])

array([200, 240, 300])

In [32]:
a = np.array([10,12,15])
b = np.array([[10],[20]])

In [33]:
a+b

array([[20, 22, 25],
       [30, 32, 35]])

In [35]:
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])
a+b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

ValueError: cannot reshape array of size 39 into shape (5,5)

In [50]:
a = np.array([0,1,2,3,4])
b = np.array([[0],[4],[14],[24],[34]])
a+b

array([[ 0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38]])

In [51]:
c=a+b
c[1::2, :3:2]

array([[ 4,  6],
       [24, 26]])

In [53]:
#주의
c[[1,3],[0,2]] # (1,0) (3,2) ,를 써서 :썼을 때와 다름

array([ 4, 26])

In [55]:
c

array([[ 0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  8],
       [14, 15, 16, 17, 18],
       [24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38]])

In [56]:
#20보다큰수만
c[c>20]

array([24, 25, 26, 27, 28, 34, 35, 36, 37, 38])

In [57]:
#3의 배수만
c[c%3==0]

array([ 0,  3,  6, 15, 18, 24, 27, 36])

In [59]:
a = np.arange(6).reshape(3,2)

In [63]:
np.tile(a,(2,3))

array([[0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3],
       [4, 5, 4, 5, 4, 5],
       [0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3],
       [4, 5, 4, 5, 4, 5]])

In [65]:
a = np.array([[2,5,4], [3,1,9], [6,8,7]]) 
a

array([[2, 5, 4],
       [3, 1, 9],
       [6, 8, 7]])

In [ ]:
254    216
319 -> 437
687    598

In [68]:
np.sort(a, axis = 1)
np.sort(a.T, axis = 0) 
전치연산(transpose)  - .T


array([[2, 1, 6],
       [4, 3, 7],
       [5, 9, 8]])

In [71]:
a = np.array([1,2,3,4])
b = np.array([[0],[7],[14],[21]])
a+b

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [15, 16, 17, 18],
       [22, 23, 24, 25]])

In [75]:
a =np.arange(1, 29).reshape(4, -1)[:4,:4]
a

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [15, 16, 17, 18],
       [22, 23, 24, 25]])

In [76]:
a[1::2,1::2]

array([[ 9, 11],
       [23, 25]])

In [82]:
a = np.arange(1,7).reshape(2,3) 
print(a)
#대각행렬을 구하는 3가지 방법
print(a.T)
print(a.transpose())
print(np.transpose(a))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [89]:
#다음배열완성하기
a = np.ones((5,5))
a[1:4,1:4] += 1
a[2,2] += 1
a

array([[1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 1.],
       [1., 2., 3., 2., 1.],
       [1., 2., 2., 2., 1.],
       [1., 1., 1., 1., 1.]])

# 수업

## 팬시 인덱싱(행따로 열따로)

- 마무리 퀴즈

In [97]:
a = np.arange(25).reshape(5,5)
a[[0,1,2,3],[1,2,3,4]] 

array([ 1,  7, 13, 19])

In [100]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.sum(a)

21

In [102]:
a.shape

(2, 3)

In [103]:
np.sum(a,axis=0)

array([5, 7, 9])

In [104]:
np.sum(a, axis=1)

array([ 6, 15])

In [105]:
# axis = 0 행 axis = 1 열

In [106]:
np.argmin(a) #인덱스(a)가 뭐일때 최소

<function numpy.argmin(a, axis=None, out=None, *, keepdims=<no value>)>

In [ ]:
raveled = flatten 쭉펴준

In [ ]:
indices  = index의 복수형

In [108]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
np.where(a %3 == 0)

(array([0, 1, 2, 2], dtype=int64), array([2, 1, 0, 3], dtype=int64))

fancyindexing으로 나옴 (0,2) (1,1) (2,0) (2,3)

In [112]:
a[np.where(a%3==0)]

array([ 3,  6,  9, 12])

In [114]:
a = np.arange(-15, 15).reshape(5,6) **2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [116]:
np.max(a,axis=1)

array([225,  81,   9,  64, 196])

In [118]:
np.mean(a,axis=0)

array([81., 76., 73., 72., 73., 76.])

### 파이썬이 느린이유

In [ ]:
파이썬 넘파이 저장방식 달라
넘파이는 c로 만들고 파이선은 아님


In [ ]:
넘파이는 몇개있는지 보고 8개가 들어갈 공간 찾아
한꺼번에 8개 집어놔
읽을때도 한번에 팍


8bit = 1byte

In [119]:
li = ( "강한샘", '곽유석', '현재은', '김경민', '권상지', '김기범', '김연준', '김인섭', '나윤찬', '남기훈', '도영현','장기영', '류소현', '문범식', '손수한', '옥윤호', '위지원', '윤민영', '장휘재', '조은정', '주기재', '황수림', 'miji') 

In [120]:
li

('강한샘',
 '곽유석',
 '현재은',
 '김경민',
 '권상지',
 '김기범',
 '김연준',
 '김인섭',
 '나윤찬',
 '남기훈',
 '도영현',
 '장기영',
 '류소현',
 '문범식',
 '손수한',
 '옥윤호',
 '위지원',
 '윤민영',
 '장휘재',
 '조은정',
 '주기재',
 '황수림',
 'miji')

In [121]:
#랜덤으로 입력받은 수만큼 사람을 중복되지 않게 뽑아서,
"1번 문제는 ooo입니다"
"2번 문제는 ooo입니다"
"3번 문제는 ooo입니다"

'3번 문제는 ooo입니다'

In [ ]:
import random 
random.sample(li, 3)

['주기재', '장휘재', '남기훈']

In [128]:
def ran(n):
    a = random.sample(li,n)
    for i in range(n):
        print(f"{i}번 문제는 {a[i]}입니다")
        

In [132]:
ran(7)

0번 문제는 김경민입니다
1번 문제는 주기재입니다
2번 문제는 남기훈입니다
3번 문제는 곽유석입니다
4번 문제는 김연준입니다
5번 문제는 miji입니다
6번 문제는 손수한입니다


series란
pandas의 1차원 자료구조