In [1]:
import numpy as np

In [7]:
li = [0,1,2,3]
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [8]:
print(a)

[0 1 2 3]


In [9]:
type(a)

numpy.ndarray

In [10]:
a.shape

(4,)

In [11]:
a.ndim

1

In [12]:
a.dtype

dtype('int32')

int8
int16
int32
int64

In [13]:
a.size

4

In [14]:
a.nbytes

16

In [15]:
1 byte 는 8bit

SyntaxError: invalid decimal literal (3029711018.py, line 1)

In [18]:
li = [0,1,2,3.0]
a = np.array(li)
a

array([0., 1., 2., 3.])

In [20]:
a.dtype

dtype('float64')

In [21]:
li = [0,1,2,3.0]
a = np.array(li, dtype = 'int32')
a

array([0, 1, 2, 3])

In [22]:
np.array([0,1,2,3])

array([0, 1, 2, 3])

In [27]:
a = np.array([[0,1,2,3],[4,5,6,7]])
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [29]:
a.shape
a.size

8

In [32]:
a = np.arange(10)
a.shape

(10,)

In [34]:
a.reshape((2,5)) #2행 5열짜리 만들어라.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
a.reshape((5,2)) 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
# 1,2,3,4
# 5,6,7,8
# 9,10,11,12

a = np.arange(1,13).reshape(3,4)

In [47]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
np.arange(1,13, dtype=np.float32).reshape(3,4)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [55]:
a = np.array([[[1,2], [3,4]],
         [[5,6], [7,8]]] 
        )

In [56]:
a.shape

(2, 2, 2)

In [59]:
np.arange(1,9).reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [61]:
np.arange(1,25).reshape(4,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [62]:
np.arange(8).reshape(4,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]],

       [[6],
        [7]]])

In [69]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
element-wise

In [70]:
a+b

array([ 6,  8, 10, 12])

In [71]:
a*b

array([ 5, 12, 21, 32])

In [74]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [75]:
a = np.array([1,2,3,4])
c = np.array([5])

In [78]:
a*c

array([ 5, 10, 15, 20])

In [79]:
a+2

array([3, 4, 5, 6])

In [82]:
a = np.arange(4).reshape(2,2)
b = np.arange(4,8).reshape(2,2)
b

array([[4, 5],
       [6, 7]])

In [85]:
a*b # array 배열의 곱셈

array([[ 0,  5],
       [12, 21]])

In [86]:
a@b #matrix 행렬의 곱셈

array([[ 6,  7],
       [26, 31]])

In [88]:
np.dot(a,b)

array([[ 6,  7],
       [26, 31]])

In [89]:
a.dot(b)

array([[ 6,  7],
       [26, 31]])

In [90]:
np.arange(5,9).reshape(2,2)

array([[5, 6],
       [7, 8]])

In [91]:
np.arange(36).reshape(3,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [93]:
a = np.array([[5,6],[7,8]])
b = np.array([[1,1], [1,1]])

In [94]:
a@b

array([[11, 11],
       [15, 15]])

In [95]:
np.dot(a,b)

array([[11, 11],
       [15, 15]])

In [96]:
a.dot(b)

array([[11, 11],
       [15, 15]])