# 시리즈

## 시리즈 만들기

In [1]:
import pandas as pd

In [2]:
animals = ['Tiger', "Bear", "Cat"]
animals

['Tiger', 'Bear', 'Cat']

In [7]:
s = pd.Series(animals)
s
# object = string = character 

0    Tiger
1     Bear
2      Cat
dtype: object

In [9]:
type(s) # 시리즈 객체

pandas.core.series.Series

In [2]:
import pandas as pd
numbers = [1,2,3]
nums = pd.Series(numbers)
print(nums)

0    1
1    2
2    3
dtype: int64


In [3]:
diction = {'a':1, 'b':2, "c":3}

In [4]:
print(diction)

{'a': 1, 'b': 2, 'c': 3}


In [5]:
d_1 = pd.Series(diction)

In [6]:
print(d_1)

a    1
b    2
c    3
dtype: int64


In [7]:
d_1['a']

1

# 데이터프레임

## 데이터프레임 만들기

In [11]:
import numpy as np
df = pd.DataFrame(np.arange(6).reshape(2,3))
df

0  1  2
0  0  1  2
1  3  4  5

In [12]:
type(df)

pandas.core.frame.DataFrame

In [14]:
pd.DataFrame({"a":[1,2], "b":2, "c":3})

a  b  c
0  1  2  3
1  2  2  3

In [22]:
pd.DataFrame([4,5,6,7], index=['a','b','c','d'], columns=["A"])

A
a  4
b  5
c  6
d  7

In [15]:
#도움말은 shift + tab

In [24]:
pd.DataFrame(np.arange(16).reshape(4,4), index=['a','b','c','d'])

0   1   2   3
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15

In [40]:
df = pd.DataFrame([[15, '남', '남중'], [17, '여', '여중']],
                 index = ['철수', '영희'],
                 columns=['나이', '성별', '학교'])
df

나이 성별  학교
철수  15  남  남중
영희  17  여  여중

In [27]:
df.index

Index(['철수', '영희'], dtype='object')

In [28]:
df.columns

Index(['나이', '성별', '학교'], dtype='object')

## 행과 열 다루기

## 삭제

In [30]:
df

나이 성별  학교
철수  15  남  남중
영희  17  여  여중

In [31]:
df.drop("철수")

나이 성별  학교
영희  17  여  여중

In [33]:
df #철수 그대로 남아있음

나이 성별  학교
철수  15  남  남중
영희  17  여  여중

In [34]:
df = df.drop("철수")
df

나이 성별  학교
영희  17  여  여중

In [36]:
df = pd.DataFrame([[15, '남', '남중'], [17, '여', '여중']],
                 index = ['철수', '영희'],
                 columns=['나이', '성별', '학교'])
df

나이 성별  학교
철수  15  남  남중
영희  17  여  여중

In [41]:
df.drop("철수", inplace=True)
df

나이 성별  학교
영희  17  여  여중

In [58]:
df = pd.DataFrame([[15, '남', '남중'], [17, '여', '여중']],
                 index = ['철수', '영희'],
                 columns=['나이', '성별', '학교'])
df

나이 성별  학교
철수  15  남  남중
영희  17  여  여중

In [51]:
df = df.iloc[[1], :]
df

나이 성별  학교
영희  17  여  여중

In [54]:
df.drop(["철수", "영희"])

Empty DataFrame
Columns: [나이, 성별, 학교]
Index: []

In [55]:
df.drop("철수", axis=0)

나이 성별  학교
영희  17  여  여중

In [56]:
df.drop("나이", axis=1)

성별  학교
철수  남  남중
영희  여  여중

In [62]:
df = pd.DataFrame([[90,98,85,100], [80,89,95,90], [70,95,100,90]],
                 index = ['서준', '우현', '인아'],
                 columns=['수학', '영어', '음악', '체육'])

In [63]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [67]:
df = pd.DataFrame({'수학': [90, 80, 70], '영어' : [98,89, 95], 
                  '음악':[85, 95, 100], '체육' : [100, 90, 90]},
                 index = ['서준', '우현', '인아']) 

In [68]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [70]:
df.columns

Index(['수학', '영어', '음악', '체육'], dtype='object')

In [72]:
a = df.values
a

array([[ 90,  98,  85, 100],
       [ 80,  89,  95,  90],
       [ 70,  95, 100,  90]], dtype=int64)

In [73]:
a[0,0]

90

In [78]:
a[1, :]
a[1]

array([80, 89, 95, 90], dtype=int64)

In [81]:
a[:,1]

array([98, 89, 95], dtype=int64)

In [82]:
df.iloc[0,0]

90

In [83]:
df.iloc[1,:]

수학    80
영어    89
음악    95
체육    90
Name: 우현, dtype: int64

In [84]:
a[:,1]

array([98, 89, 95], dtype=int64)

df는 array가 아니다.

In [86]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [87]:
df.iloc[0, :]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

loc: location<BR>
iloc: integer location 

In [90]:
df.loc[['서준','우현'], :]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [94]:
df.iloc[:2,]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [97]:
df.loc['서준', :]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [101]:
df.loc[['서준'], :] #하나여도 괄호 넣으면 output 깔끔히 나옴

수학  영어  음악   체육
서준  90  98  85  100

In [108]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

1. 수학, 영어 두 칼럼만

In [107]:
df.iloc[:,:2]

수학  영어
서준  90  98
우현  80  89
인아  70  95

2. 수학칼럼만 데이터프레임으로

In [109]:
df.iloc[:, [0]]

수학
서준  90
우현  80
인아  70

In [110]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [113]:
df.loc['서준'] # 
df.loc[['서준']]

수학  영어  음악   체육
서준  90  98  85  100

In [121]:
df.loc[:,['수학']] #열은 안돼
#df.loc['서준', :]

수학
서준  90
우현  80
인아  70

In [123]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [127]:
df.iloc[[1]]
df.iloc[[1], :] #두 개 똑같

수학  영어  음악  체육
우현  80  89  95  90

In [129]:
df.loc['서준'] #행은 loc안쓰면 오류나
df['수학'] #컬럼은 loc없어도 가능

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [131]:
df.수학 #컬럼만 가능

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [133]:
df[['수학', '영어']]

수학  영어
서준  90  98
우현  80  89
인아  70  95

In [134]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [135]:
df.loc['서준']

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [137]:
df.iloc[[1]]

수학  영어  음악  체육
우현  80  89  95  90

In [139]:
df.iloc[::2, :]

수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

## 이름 바꾸기

In [142]:
df.index

Index(['서준', '우현', '인아'], dtype='object')


In [145]:
df.index = ['준', '현', '아']
df

수학  영어   음악   체육
준  90  98   85  100
현  80  89   95   90
아  70  95  100   90

In [149]:
df.index[1] = "우현"

TypeError: Index does not support mutable operations

In [150]:
df.index = ['서준', '우현', '인아']

In [151]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [152]:
df.columns

Index(['수학', '영어', '음악', '체육'], dtype='object')

In [155]:
df.columns = ['수학', '영어', '음악', '체육']

In [156]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [160]:
df.rename(columns={"체육":"체"}, inplace=True)

In [165]:
df.rename({'체': '체육'}, axis=1, inplace=True)

In [166]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

- 연습

In [195]:
import plotly.express as px
df = px.data.gapminder()
df.head()
df

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [196]:
df.shape

(1704, 8)

In [197]:
df.head()

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4

In [198]:
df.head(10)

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
5  Afghanistan      Asia  1977   38.438  14880372  786.113360       AFG   
6  Afghanistan      Asia  1982   39.854  12881816  978.011439       AFG   
7  Afghanistan      Asia  1987   40.822  13867957  852.395945       AFG   
8  Afghanistan      Asia  1992   41.674  16317921  649.341395       AFG   
9  Afghanistan      Asia  1997   41.763  22227415  635.341351       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4  
5        4  
6        4  
7        4  
8        4  
9        4

In [199]:
df.iloc[:10, :]

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
5  Afghanistan      Asia  1977   38.438  14880372  786.113360       AFG   
6  Afghanistan      Asia  1982   39.854  12881816  978.011439       AFG   
7  Afghanistan      Asia  1987   40.822  13867957  852.395945       AFG   
8  Afghanistan      Asia  1992   41.674  16317921  649.341395       AFG   
9  Afghanistan      Asia  1997   41.763  22227415  635.341351       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4  
5        4  
6        4  
7        4  
8        4  
9        4

In [200]:
df[:10]

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
5  Afghanistan      Asia  1977   38.438  14880372  786.113360       AFG   
6  Afghanistan      Asia  1982   39.854  12881816  978.011439       AFG   
7  Afghanistan      Asia  1987   40.822  13867957  852.395945       AFG   
8  Afghanistan      Asia  1992   41.674  16317921  649.341395       AFG   
9  Afghanistan      Asia  1997   41.763  22227415  635.341351       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4  
5        4  
6        4  
7        4  
8        4  
9        4

In [201]:
df.tail(10)

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
1694  Zimbabwe    Africa  1962   52.358   4277736  527.272182       ZWE   
1695  Zimbabwe    Africa  1967   53.995   4995432  569.795071       ZWE   
1696  Zimbabwe    Africa  1972   55.635   5861135  799.362176       ZWE   
1697  Zimbabwe    Africa  1977   57.674   6642107  685.587682       ZWE   
1698  Zimbabwe    Africa  1982   60.363   7636524  788.855041       ZWE   
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
1694      716  
1695      716  
1696      716  
1697      716  
1698      716  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716

In [202]:
df[-10:]

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
1694  Zimbabwe    Africa  1962   52.358   4277736  527.272182       ZWE   
1695  Zimbabwe    Africa  1967   53.995   4995432  569.795071       ZWE   
1696  Zimbabwe    Africa  1972   55.635   5861135  799.362176       ZWE   
1697  Zimbabwe    Africa  1977   57.674   6642107  685.587682       ZWE   
1698  Zimbabwe    Africa  1982   60.363   7636524  788.855041       ZWE   
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
1694      716  
1695      716  
1696      716  
1697      716  
1698      716  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716

In [203]:
df.iloc[[100,200,300,400,500]]
df.iloc[[100,200,300,400,500], :]
df.iloc[100:501:100]

country continent  year  lifeExp       pop     gdpPercap  \
100      Bangladesh      Asia  1972   45.252  70759295    630.233627   
200    Burkina Faso    Africa  1992   50.260   8878303    931.752773   
300        Colombia  Americas  1952   50.643  12350771   2144.115096   
400  Czech Republic    Europe  1972   70.290   9862158  13108.453600   
500         Eritrea    Africa  1992   49.991   3668440    582.858510   

    iso_alpha  iso_num  
100       BGD       50  
200       BFA      854  
300       COL      170  
400       CZE      203  
500       ERI      232

In [204]:
df = df.iloc[100:501:100, :]
df

country continent  year  lifeExp       pop     gdpPercap  \
100      Bangladesh      Asia  1972   45.252  70759295    630.233627   
200    Burkina Faso    Africa  1992   50.260   8878303    931.752773   
300        Colombia  Americas  1952   50.643  12350771   2144.115096   
400  Czech Republic    Europe  1972   70.290   9862158  13108.453600   
500         Eritrea    Africa  1992   49.991   3668440    582.858510   

    iso_alpha  iso_num  
100       BGD       50  
200       BFA      854  
300       COL      170  
400       CZE      203  
500       ERI      232

In [205]:
df.iloc[:, :5]

country continent  year  lifeExp       pop
100      Bangladesh      Asia  1972   45.252  70759295
200    Burkina Faso    Africa  1992   50.260   8878303
300        Colombia  Americas  1952   50.643  12350771
400  Czech Republic    Europe  1972   70.290   9862158
500         Eritrea    Africa  1992   49.991   3668440